# Generated by Django 3.2.6 on 2021-08-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20210811_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
